apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejsapp-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/madlopt/test
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
