apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v2.22.1
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
    limits:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v2.22.1
  serviceMonitorSelector:
    matchExpressions:
      - {key: app, operator: In, values: [nodejsapp, goapp, phpapp, anyapp, prometheus]}
  podMonitorSelector:
    matchExpressions:
      - {key: app, operator: In, values: [nodejsapp, goapp, phpapp, anyapp, prometheus]}