{
 "title": "Applications Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "App Request Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (changes(http_requests_counter[$__range]))",
     "legendFormat": "pod - {{pod}}"
    }
   ]
  },
  {
   "title": "Resident memory usage by Instance",
   "type": "timeseries",
   "description": "This excludes swapped out memory pages",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container, instance) (process_resident_memory_bytes)",
     "legendFormat": "{{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (changes(http_requests_counter[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Restart Times (1m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage (all cores)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "User CPU - {{container}} - {{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "Sys CPU - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Restart Times by Instance app (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (changes(process_start_time_seconds[1m])) by(instance, pod)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(major, minor, patch) (nodejs_version_info)",
     "legendFormat": "{{major}}.{{minor}}.{{patch}}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(go_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Go Apps Memory Allocated Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total", "legendFormat": "{{pod}} - {{instance}}" }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}