apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejapp-metrics
  labels:
    app: nodejsapp
spec:
  selector:
    matchLabels:
      app: nodejsapp
  podMetricsEndpoints:
    - targetPort: 80
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
      path: /metrics
