apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - image: madloptus/nodejsapp:latest
        name: nodejsapp
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
