apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejapp-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejsapp
  namespaceSelector:
    matchNames:
      - dev
  podMetricsEndpoints:
    - targetPort: 80
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
      path: /metrics
