apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejsapp-metrics
  labels:
    app: nodejsapp
    release: kube-prometheus-stack
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      scheme: http
      scrapeTimeout: 14s
      port: web
  selector:
    matchLabels:
      release: kube-prometheus-stack
