apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejsapp-pod-monitor
  labels:
    app: nodejsapp
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejsapp
  podMetricsEndpoints:
    - port: web