apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejapp-pod-monitor
  labels:
    app: nodejsapp
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejsapp
  podMetricsEndpoints:
    - port: web
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
      path: /metrics