apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejapp-pod-monitor
  labels:
    app: nodejsapp
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      app: nodejsapp