apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nodejsapp-pod-monitor
  labels:
    app: nodejsapp
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      scheme: http
      scrapeTimeout: 14s
      port: web
      honorLabels: true
  selector:
    matchLabels:
      app: nodejsapp
