apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejsapp-service-monitor
  labels:
    app: nodejsapp
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      release: kube-prometheus-stack