{
 "title": "Odds Delivery NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [
  "nodejs",
  "odds-delivery"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Re-connection by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (changes(connection_retry_counter_per_daemon_session{metadata_component=\"odds-delivery\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident memory usage by Instance",
   "type": "timeseries",
   "description": "This excludes swapped out memory pages",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_resident_memory_bytes{metadata_component=\"odds-delivery\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total memory usage by all Odds Delivery Daemons",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(nodejs_external_memory_bytes{metadata_component=\"odds-delivery\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Re-connection Rate (1m) by ConnectionEngine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(connection_engine) (rate(connection_retry_counter_per_daemon_session{metadata_component=\"odds-delivery\"}[1m]))",
     "legendFormat": "{{connectionEngine}}"
    }
   ]
  },
  {
   "title": "Process Restart Times by Instance (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (changes(process_start_time_seconds{metadata_component=\"odds-delivery\"}[1m])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Restart Times (1m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Odds Delivery Re-connection Rate (1m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(connection_retry_counter_per_daemon_session{metadata_component=\"odds-delivery\"}[1m]))"
    }
   ]
  },
  {
   "title": "HealthCheck Down reports by Instance",
   "type": "timeseries",
   "description": "How many times the health check was requested and reported the down status",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "healthcheck_down_report_per_daemon_session{metadata_component=\"odds-delivery\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "External Memory - {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "RAM + Swap - {{instance}}"
    }
   ]
  },
  {
   "title": "Messages processed Total",
   "type": "stat",
   "description": "Messages processed by all of the daemons for given period of time",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(messages_processed_by_daemon{metadata_component=\"odds-delivery\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Exit received by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "exit_counter_per_daemon_session{metadata_component=\"odds-delivery\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(major, minor, patch) (nodejs_version_info{metadata_component=\"odds-delivery\"})",
     "legendFormat": "{{major}}.{{minor}}.{{patch}}"
    }
   ]
  },
  {
   "title": "V8 Heap Size Total Available by Instance",
   "type": "timeseries",
   "description": "The number that shows what V8 engine think is available for him. Default is 2.18Gb.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nodejs_v8_heap_size_total_available_bytes{metadata_component=\"odds-delivery\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages processed by Instance (1m)",
   "type": "timeseries",
   "description": "Messages processed by daemon per 1 minute",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (changes(messages_processed_by_daemon{metadata_component=\"odds-delivery\"}[1m]))",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "V8 Heap Size Limit by Instance",
   "type": "timeseries",
   "description": "nodejs_v8_heap_size_limit_bytes",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nodejs_v8_heap_size_limit_bytes{metadata_component=\"odds-delivery\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Mongo message size by Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_mongo_message_size_by_daemon{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Max Mongo chunk message size by Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_mongo_chunk_message_size_by_daemon{metadata_component=\"odds-delivery\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "CPU Usage (all cores)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{metadata_component=\"odds-delivery\"}[1m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{metadata_component=\"odds-delivery\"}[1m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  }
 ]
}