apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goapp-service-monitor
  labels:
    app: goapp
spec:
  endpoints:
    - interval: 15s
      port: web
  selector:
    matchLabels:
      app: goapp